// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYt2Y_APIetQ7tMBOI-_860KIQ_xAyuhI',
    appId: '1:779288011889:web:02c503932abee26bc4a7d0',
    messagingSenderId: '779288011889',
    projectId: 'dietgram-fe976',
    authDomain: 'dietgram-fe976.firebaseapp.com',
    storageBucket: 'dietgram-fe976.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYt2Y_APIetQ7tMBOI-_860KIQ_xAyuhI',
    appId: '1:779288011889:android:02c503932abee26bc4a7d0',
    messagingSenderId: '779288011889',
    projectId: 'dietgram-fe976',
    storageBucket: 'dietgram-fe976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYt2Y_APIetQ7tMBOI-_860KIQ_xAyuhI',
    appId: '1:779288011889:ios:02c503932abee26bc4a7d0',
    messagingSenderId: '779288011889',
    projectId: 'dietgram-fe976',
    storageBucket: 'dietgram-fe976.firebasestorage.app',
    iosBundleId: 'com.example.dietgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYt2Y_APIetQ7tMBOI-_860KIQ_xAyuhI',
    appId: '1:779288011889:macos:02c503932abee26bc4a7d0',
    messagingSenderId: '779288011889',
    projectId: 'dietgram-fe976',
    storageBucket: 'dietgram-fe976.firebasestorage.app',
    iosBundleId: 'com.example.dietgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYt2Y_APIetQ7tMBOI-_860KIQ_xAyuhI',
    appId: '1:779288011889:windows:02c503932abee26bc4a7d0',
    messagingSenderId: '779288011889',
    projectId: 'dietgram-fe976',
    authDomain: 'dietgram-fe976.firebaseapp.com',
    storageBucket: 'dietgram-fe976.firebasestorage.app',
  );
} 